version: "3"
services:
  server:
    image: domjudge/domserver:latest
    hostname: jutgeserver
    env_file:
      jutgeserver.env
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - .:/domjudge:cached
    links:
      - db:mariadb
    depends_on:
      - db
    ports: 
      - 80:80
    restart: on-failure
    privileged: true

  db:
    image: mariadb
    env_file:
      jutgeserver.env
    ports:
      - 13306:3306
    command: --max-connections=500 --max-allowed-packet=512M
    volumes:
      - /var/lib/mysql
