version: "3.9"
services:
  jutgehost:
    image: domjudge/judgehost:latest
    hostname: $JUDGEHOST_NAME
    container_name: $JUDGEHOST_NAME
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    environment:
      - CONTAINER_TIMEZONE=Europe/Madrid
      - DOMSERVER_BASEURL=zombies.itb.cat/
      - JUDGEDAEMON_USERNAME=judgehost
      - JUDGEDAEMON_PASSWORD=host1234
      - DOMJUDGE_CREATE_WRITABLE_TEMP_DIR=1
    privileged: true
